/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 * Vista Principal
 *
 * @author freew
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemInicio = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemMonitor = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemSocio = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemActividad = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItemInscripcion = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Inicio");

        jMenuItemInicio.setText("Volver a la página principal");
        jMenuItemInicio.setActionCommand("Inicio");
        jMenuItemInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInicioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemInicio);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Monitores");

        jMenuItemMonitor.setText("Gestión de Monitores");
        jMenuItemMonitor.setActionCommand("GestionMonitores");
        jMenuItemMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMonitorActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemMonitor);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Socios");

        jMenuItemSocio.setText("Gestión de Socios");
        jMenuItemSocio.setActionCommand("GestionSocios");
        jMenuItemSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSocioActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemSocio);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Actividades");

        jMenuItemActividad.setText("Gestión de Actividades");
        jMenuItemActividad.setActionCommand("GestionActividades");
        jMenu4.add(jMenuItemActividad);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Inscripción");
        jMenu6.setActionCommand("Inscripcion");

        jMenuItemInscripcion.setText("Gestión de Inscripciones");
        jMenuItemInscripcion.setActionCommand("GestionInscripciones");
        jMenu6.add(jMenuItemInscripcion);

        jMenuBar1.add(jMenu6);

        jMenu5.setText("Salir");

        jMenuItemSalir.setText("Salir de la aplicación");
        jMenuItemSalir.setActionCommand("Salir");
        jMenu5.add(jMenuItemSalir);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemInicioActionPerformed

    private void jMenuItemMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMonitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemMonitorActionPerformed

    private void jMenuItemSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSocioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItemActividad;
    public javax.swing.JMenuItem jMenuItemInicio;
    public javax.swing.JMenuItem jMenuItemInscripcion;
    public javax.swing.JMenuItem jMenuItemMonitor;
    public javax.swing.JMenuItem jMenuItemSalir;
    public javax.swing.JMenuItem jMenuItemSocio;
    // End of variables declaration//GEN-END:variables
}
